# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-18 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compute', models.CharField(max_length=255)),
            ],
        ),
    ]
