# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-08 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0009_area_compute_result_area_month_count_operator_compute_result_operator_month_count_service_line_compu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area_compute_result',
        ),
        migrations.DeleteModel(
            name='Area_month_count',
        ),
        migrations.DeleteModel(
            name='Operator_compute_result',
        ),
        migrations.DeleteModel(
            name='Operator_month_count',
        ),
        migrations.DeleteModel(
            name='Service_line_compute_result',
        ),
    ]
