# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-09 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0011_area_compute_result_area_month_count_operator_compute_result_operator_month_count_service_line_compu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_line_month_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_line', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('operator', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('max_value', models.FloatField(blank=True, default=None)),
                ('average_value', models.FloatField(blank=True, default=None)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
