# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-16 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0012_service_line_month_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
    ]
